import type { SiteTheme } from "@/types/theme";

export interface ThemePreset {
  name: string;
  nameAr: string;
  theme: Omit<SiteTheme, "direction">;
}

export const themePresets: ThemePreset[] = [
  {
    name: "Ocean Blue",
    nameAr: "أزرق محيطي",
    theme: {
      colors: {
        primary: "#2563EB",
        primaryForeground: "#FFFFFF",
        secondary: "#7C3AED",
        secondaryForeground: "#FFFFFF",
        accent: "#F59E0B",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#0F172A",
        muted: "#F1F5F9",
        mutedForeground: "#64748B",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        border: "#E2E8F0",
        ring: "#2563EB",
        success: "#16A34A",
        warning: "#EAB308",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-inter)",
        body: "var(--font-inter)",
      },
      borderRadius: "md",
    },
  },
  {
    name: "Emerald",
    nameAr: "زمردي",
    theme: {
      colors: {
        primary: "#059669",
        primaryForeground: "#FFFFFF",
        secondary: "#0891B2",
        secondaryForeground: "#FFFFFF",
        accent: "#D97706",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#064E3B",
        muted: "#F0FDF4",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#064E3B",
        border: "#D1FAE5",
        ring: "#059669",
        success: "#16A34A",
        warning: "#EAB308",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-rubik)",
        body: "var(--font-rubik)",
      },
      borderRadius: "lg",
    },
  },
  {
    name: "Rose Gold",
    nameAr: "ذهبي وردي",
    theme: {
      colors: {
        primary: "#E11D48",
        primaryForeground: "#FFFFFF",
        secondary: "#BE185D",
        secondaryForeground: "#FFFFFF",
        accent: "#F59E0B",
        accentForeground: "#FFFFFF",
        background: "#FFFBF5",
        foreground: "#1C1917",
        muted: "#FFF1F2",
        mutedForeground: "#78716C",
        card: "#FFFFFF",
        cardForeground: "#1C1917",
        border: "#FECDD3",
        ring: "#E11D48",
        success: "#16A34A",
        warning: "#EAB308",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-readex-pro)",
        body: "var(--font-readex-pro)",
      },
      borderRadius: "md",
    },
  },
  {
    name: "Midnight",
    nameAr: "منتصف الليل",
    theme: {
      colors: {
        primary: "#818CF8",
        primaryForeground: "#0F172A",
        secondary: "#A78BFA",
        secondaryForeground: "#0F172A",
        accent: "#34D399",
        accentForeground: "#0F172A",
        background: "#0F172A",
        foreground: "#F8FAFC",
        muted: "#1E293B",
        mutedForeground: "#94A3B8",
        card: "#1E293B",
        cardForeground: "#F8FAFC",
        border: "#334155",
        ring: "#818CF8",
        success: "#34D399",
        warning: "#FBBF24",
        destructive: "#F87171",
      },
      fonts: {
        heading: "var(--font-inter)",
        body: "var(--font-inter)",
      },
      borderRadius: "lg",
    },
  },
  {
    name: "Saudi Green",
    nameAr: "أخضر سعودي",
    theme: {
      colors: {
        primary: "#006C35",
        primaryForeground: "#FFFFFF",
        secondary: "#1A8B4E",
        secondaryForeground: "#FFFFFF",
        accent: "#C8A951",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#1A1A2E",
        muted: "#F0F9F4",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#1A1A2E",
        border: "#D1E7DD",
        ring: "#006C35",
        success: "#16A34A",
        warning: "#EAB308",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-cairo)",
        body: "var(--font-cairo)",
      },
      borderRadius: "md",
    },
  },
  {
    name: "Warm Sunset",
    nameAr: "غروب دافئ",
    theme: {
      colors: {
        primary: "#EA580C",
        primaryForeground: "#FFFFFF",
        secondary: "#DC2626",
        secondaryForeground: "#FFFFFF",
        accent: "#FBBF24",
        accentForeground: "#1C1917",
        background: "#FFFBEB",
        foreground: "#1C1917",
        muted: "#FEF3C7",
        mutedForeground: "#78716C",
        card: "#FFFFFF",
        cardForeground: "#1C1917",
        border: "#FED7AA",
        ring: "#EA580C",
        success: "#16A34A",
        warning: "#F59E0B",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-changa)",
        body: "var(--font-tajawal)",
      },
      borderRadius: "sm",
    },
  },
  {
    name: "Royal Purple",
    nameAr: "بنفسجي ملكي",
    theme: {
      colors: {
        primary: "#7C3AED",
        primaryForeground: "#FFFFFF",
        secondary: "#6D28D9",
        secondaryForeground: "#FFFFFF",
        accent: "#EC4899",
        accentForeground: "#FFFFFF",
        background: "#FAFAFE",
        foreground: "#1E1B4B",
        muted: "#F5F3FF",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#1E1B4B",
        border: "#E9D5FF",
        ring: "#7C3AED",
        success: "#10B981",
        warning: "#F59E0B",
        destructive: "#EF4444",
      },
      fonts: {
        heading: "var(--font-almarai)",
        body: "var(--font-almarai)",
      },
      borderRadius: "lg",
    },
  },
  {
    name: "Charcoal",
    nameAr: "فحمي داكن",
    theme: {
      colors: {
        primary: "#F8FAFC",
        primaryForeground: "#09090B",
        secondary: "#A1A1AA",
        secondaryForeground: "#09090B",
        accent: "#FBBF24",
        accentForeground: "#09090B",
        background: "#09090B",
        foreground: "#FAFAFA",
        muted: "#18181B",
        mutedForeground: "#A1A1AA",
        card: "#18181B",
        cardForeground: "#FAFAFA",
        border: "#27272A",
        ring: "#F8FAFC",
        success: "#4ADE80",
        warning: "#FBBF24",
        destructive: "#FB7185",
      },
      fonts: {
        heading: "var(--font-ibm-plex-arabic)",
        body: "var(--font-ibm-plex-arabic)",
      },
      borderRadius: "sm",
    },
  },
  {
    name: "Teal Fresh",
    nameAr: "أزرق مخضر",
    theme: {
      colors: {
        primary: "#0D9488",
        primaryForeground: "#FFFFFF",
        secondary: "#0891B2",
        secondaryForeground: "#FFFFFF",
        accent: "#F97316",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#134E4A",
        muted: "#F0FDFA",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#134E4A",
        border: "#CCFBF1",
        ring: "#0D9488",
        success: "#059669",
        warning: "#EAB308",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-noto-sans-arabic)",
        body: "var(--font-noto-sans-arabic)",
      },
      borderRadius: "md",
    },
  },
  {
    name: "Coral Reef",
    nameAr: "مرجاني",
    theme: {
      colors: {
        primary: "#F43F5E",
        primaryForeground: "#FFFFFF",
        secondary: "#FB923C",
        secondaryForeground: "#FFFFFF",
        accent: "#A855F7",
        accentForeground: "#FFFFFF",
        background: "#FFFBFB",
        foreground: "#1F2937",
        muted: "#FFF1F2",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#1F2937",
        border: "#FECDD3",
        ring: "#F43F5E",
        success: "#10B981",
        warning: "#F59E0B",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-el-messiri)",
        body: "var(--font-cairo)",
      },
      borderRadius: "lg",
    },
  },
  {
    name: "Desert Sand",
    nameAr: "رمال صحراوية",
    theme: {
      colors: {
        primary: "#92400E",
        primaryForeground: "#FFFFFF",
        secondary: "#B45309",
        secondaryForeground: "#FFFFFF",
        accent: "#0D9488",
        accentForeground: "#FFFFFF",
        background: "#FEFCE8",
        foreground: "#422006",
        muted: "#FEF9C3",
        mutedForeground: "#78716C",
        card: "#FFFEF5",
        cardForeground: "#422006",
        border: "#FDE68A",
        ring: "#92400E",
        success: "#16A34A",
        warning: "#CA8A04",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-tajawal)",
        body: "var(--font-tajawal)",
      },
      borderRadius: "md",
    },
  },
  {
    name: "Navy Gold",
    nameAr: "كحلي ذهبي",
    theme: {
      colors: {
        primary: "#1E3A5F",
        primaryForeground: "#FFFFFF",
        secondary: "#2563EB",
        secondaryForeground: "#FFFFFF",
        accent: "#D4AF37",
        accentForeground: "#1E3A5F",
        background: "#FFFFFF",
        foreground: "#0C1929",
        muted: "#F0F4F8",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#0C1929",
        border: "#D1D9E6",
        ring: "#1E3A5F",
        success: "#16A34A",
        warning: "#EAB308",
        destructive: "#DC2626",
      },
      fonts: {
        heading: "var(--font-amiri)",
        body: "var(--font-inter)",
      },
      borderRadius: "sm",
    },
  },
];

/**
 * Available fonts — all self-hosted via next/font/google.
 * Values are CSS variable references that resolve to the actual font-family string.
 */
export const availableFonts = [
  { value: "var(--font-inter)", label: "Inter", labelAr: "إنتر", category: "sans-serif" as const },
  { value: "var(--font-cairo)", label: "Cairo", labelAr: "القاهرة", category: "sans-serif" as const },
  { value: "var(--font-tajawal)", label: "Tajawal", labelAr: "تجوال", category: "sans-serif" as const },
  { value: "var(--font-almarai)", label: "Almarai", labelAr: "المراعي", category: "sans-serif" as const },
  { value: "var(--font-rubik)", label: "Rubik", labelAr: "روبيك", category: "sans-serif" as const },
  { value: "var(--font-noto-sans-arabic)", label: "Noto Sans Arabic", labelAr: "نوتو سانس عربي", category: "sans-serif" as const },
  { value: "var(--font-ibm-plex-arabic)", label: "IBM Plex Arabic", labelAr: "آي بي إم بلكس عربي", category: "sans-serif" as const },
  { value: "var(--font-readex-pro)", label: "Readex Pro", labelAr: "ريدكس برو", category: "sans-serif" as const },
  { value: "var(--font-el-messiri)", label: "El Messiri", labelAr: "المسيري", category: "sans-serif" as const },
  { value: "var(--font-amiri)", label: "Amiri", labelAr: "أميري", category: "serif" as const },
  { value: "var(--font-changa)", label: "Changa", labelAr: "شانجا", category: "sans-serif" as const },
];
